--
-- PostgreSQL database dump
--

\restrict j6qf2hlVzrtOLcUXdttANGuNAR9sdo0NaHYDR5O6Cliwdb12ooXH5Tdel0Za3V0

-- Dumped from database version 17.7 (Debian 17.7-3.pgdg13+1)
-- Dumped by pg_dump version 17.6 (Homebrew)

-- Started on 2025-12-22 13:01:51 IST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3442 (class 1262 OID 16384)
-- Name: ledgerdb; Type: DATABASE; Schema: -; Owner: ledger
--

CREATE DATABASE ledgerdb WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE ledgerdb OWNER TO ledger;

\unrestrict j6qf2hlVzrtOLcUXdttANGuNAR9sdo0NaHYDR5O6Cliwdb12ooXH5Tdel0Za3V0
\connect ledgerdb
\restrict j6qf2hlVzrtOLcUXdttANGuNAR9sdo0NaHYDR5O6Cliwdb12ooXH5Tdel0Za3V0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3443 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16390)
-- Name: events; Type: TABLE; Schema: public; Owner: ledger
--

CREATE TABLE public.events (
    id bigint NOT NULL,
    account_id character varying(255),
    amount double precision NOT NULL,
    event_id character varying(255) NOT NULL,
    "timestamp" bigint,
    type character varying(255)
);


ALTER TABLE public.events OWNER TO ledger;

--
-- TOC entry 217 (class 1259 OID 16389)
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: ledger
--

ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16400)
-- Name: ledger_entries; Type: TABLE; Schema: public; Owner: ledger
--

CREATE TABLE public.ledger_entries (
    id bigint NOT NULL,
    account_id character varying(255),
    amount numeric(38,2),
    event_id character varying(255),
    "timestamp" timestamp(6) with time zone,
    type character varying(255),
    CONSTRAINT ledger_entries_type_check CHECK (((type)::text = ANY ((ARRAY['debit'::character varying, 'credit'::character varying])::text[])))
);


ALTER TABLE public.ledger_entries OWNER TO ledger;

--
-- TOC entry 219 (class 1259 OID 16399)
-- Name: ledger_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: ledger
--

ALTER TABLE public.ledger_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ledger_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3434 (class 0 OID 16390)
-- Dependencies: 218
-- Data for Name: events; Type: TABLE DATA; Schema: public; Owner: ledger
--

INSERT INTO public.events VALUES (23, 'A20', 500, 'E2001', 1735561800000, 'credit');
INSERT INTO public.events VALUES (24, 'A10', 500, 'E1001', 1735561800000, 'credit');
INSERT INTO public.events VALUES (25, 'A10', 500, 'E1002', 1735561800000, 'credit');
INSERT INTO public.events VALUES (26, 'A20', 500, 'E1000', 1735561800000, 'credit');
INSERT INTO public.events VALUES (27, 'A10', 1000, 'E-1766382702-1', 1766382728000, 'credit');
INSERT INTO public.events VALUES (28, 'A10', 250, 'E-1766382702-2', 1766382728000, 'debit');
INSERT INTO public.events VALUES (29, 'A-1766382989', 1000, 'E-1766382989-1', 1766383015000, 'credit');
INSERT INTO public.events VALUES (30, 'A-1766382989', 250, 'E-1766382989-2', 1766383015000, 'debit');
INSERT INTO public.events VALUES (31, 'A10', 1000, 'E-1766383080-1', 1766383105000, 'credit');
INSERT INTO public.events VALUES (32, 'A10', 250, 'E-1766383080-2', 1766383105000, 'debit');


--
-- TOC entry 3436 (class 0 OID 16400)
-- Dependencies: 220
-- Data for Name: ledger_entries; Type: TABLE DATA; Schema: public; Owner: ledger
--

INSERT INTO public.ledger_entries VALUES (1, 'acc-14', 5000.00, 'evt-006', '2024-12-14 15:10:00+00', 'credit');
INSERT INTO public.ledger_entries VALUES (2, 'acc-14', 5000.00, 'evt-007', '2024-12-14 15:10:00+00', 'credit');
INSERT INTO public.ledger_entries VALUES (3, 'acc-14', 5000.00, 'evt-008', '2024-12-14 15:10:00+00', 'credit');
INSERT INTO public.ledger_entries VALUES (4, 'acc-15', 5000.00, 'evt-009', '2024-12-14 15:10:00+00', 'credit');
INSERT INTO public.ledger_entries VALUES (5, 'acc-15', 5000.00, 'evt-010', '2024-12-14 15:10:00+00', 'credit');
INSERT INTO public.ledger_entries VALUES (6, 'acc-15', 500.00, 'MANUAL-69ec4312-5c96-4d3d-a135-634f5c17c54d', '2025-12-21 07:06:58.256+00', 'credit');
INSERT INTO public.ledger_entries VALUES (7, 'acc-15', 5000.00, 'evt-015', '2024-12-14 15:10:00+00', 'credit');
INSERT INTO public.ledger_entries VALUES (8, 'acc-15', 5000.00, 'evt-016', '2024-12-14 15:10:00+00', 'credit');
INSERT INTO public.ledger_entries VALUES (9, 'acc-15', 5000.00, 'evt-017', '2024-12-14 15:10:00+00', 'credit');
INSERT INTO public.ledger_entries VALUES (10, 'acc-15', 5000.00, 'evt-018', '2024-12-14 15:10:00+00', 'credit');
INSERT INTO public.ledger_entries VALUES (11, 'acc-16', 5000.00, 'evt-019', '2024-12-14 15:10:00+00', 'credit');
INSERT INTO public.ledger_entries VALUES (12, 'acc-16', 500.00, 'MANUAL-e3f6a4c1-07eb-4e87-a416-c67f7d0b1116', '2025-12-21 09:18:35.311+00', 'credit');
INSERT INTO public.ledger_entries VALUES (13, 'acc-16', 5000.00, 'MANUAL-8fa44118-c72c-4358-b8e1-a92f6923d0a1', '2025-12-21 09:18:51.354+00', 'credit');
INSERT INTO public.ledger_entries VALUES (14, 'A10', 500.00, 'E1001', '2024-12-30 12:30:00+00', 'credit');
INSERT INTO public.ledger_entries VALUES (15, 'A30', 500.00, 'E3001', '2024-12-30 12:30:00+00', 'credit');
INSERT INTO public.ledger_entries VALUES (16, 'A20', 500.00, 'E2001', '2024-12-30 12:30:00+00', 'credit');
INSERT INTO public.ledger_entries VALUES (17, 'A10', 500.00, 'E1002', '2024-12-30 12:30:00+00', 'credit');
INSERT INTO public.ledger_entries VALUES (18, 'A20', 500.00, 'E1000', '2024-12-30 12:30:00+00', 'credit');
INSERT INTO public.ledger_entries VALUES (38, 'A10', 50.00, 'MANUAL-d6e7b20d-12c3-408e-aa2a-205a02e59d7f', '2025-12-22 05:47:17.597+00', 'credit');
INSERT INTO public.ledger_entries VALUES (39, 'A10', 1000.00, 'E-1766382702-1', '2025-12-22 05:52:08+00', 'credit');
INSERT INTO public.ledger_entries VALUES (40, 'A10', 50.00, 'MANUAL-24783423-f028-4913-a67b-835e21eb77d6', '2025-12-22 05:52:28.712+00', 'credit');
INSERT INTO public.ledger_entries VALUES (41, 'A-1766382989', 1000.00, 'E-1766382989-1', '2025-12-22 05:56:55+00', 'credit');
INSERT INTO public.ledger_entries VALUES (42, 'A10', 1000.00, 'E-1766383080-1', '2025-12-22 05:58:25+00', 'credit');
INSERT INTO public.ledger_entries VALUES (43, 'A10', 50.00, 'MANUAL-bf9635d1-6bce-47b6-8aef-7660f0331581', '2025-12-22 05:58:46.11+00', 'credit');


--
-- TOC entry 3444 (class 0 OID 0)
-- Dependencies: 217
-- Name: events_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ledger
--

SELECT pg_catalog.setval('public.events_id_seq', 32, true);


--
-- TOC entry 3445 (class 0 OID 0)
-- Dependencies: 219
-- Name: ledger_entries_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ledger
--

SELECT pg_catalog.setval('public.ledger_entries_id_seq', 43, true);


--
-- TOC entry 3281 (class 2606 OID 16396)
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: ledger
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- TOC entry 3285 (class 2606 OID 16407)
-- Name: ledger_entries ledger_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: ledger
--

ALTER TABLE ONLY public.ledger_entries
    ADD CONSTRAINT ledger_entries_pkey PRIMARY KEY (id);


--
-- TOC entry 3283 (class 2606 OID 16398)
-- Name: events ukfetcx6iyme0h8x139fwn8lt12; Type: CONSTRAINT; Schema: public; Owner: ledger
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT ukfetcx6iyme0h8x139fwn8lt12 UNIQUE (event_id);


--
-- TOC entry 3287 (class 2606 OID 16409)
-- Name: ledger_entries ukghh2tfa9wancvr3r25m8w27rb; Type: CONSTRAINT; Schema: public; Owner: ledger
--

ALTER TABLE ONLY public.ledger_entries
    ADD CONSTRAINT ukghh2tfa9wancvr3r25m8w27rb UNIQUE (event_id);


-- Completed on 2025-12-22 13:01:51 IST

--
-- PostgreSQL database dump complete
--

\unrestrict j6qf2hlVzrtOLcUXdttANGuNAR9sdo0NaHYDR5O6Cliwdb12ooXH5Tdel0Za3V0

